import { env } from "../config/env.js";

// OAuth設定（Gmail専用のOAuthクライアント）
const GMAIL_CONFIG = {
  clientId: env.GMAIL_CLIENT_ID || "",
  clientSecret: env.GMAIL_CLIENT_SECRET || "",
  refreshToken: env.GMAIL_REFRESH_TOKEN || "",
};

// --- OAuth ---

async function getAccessToken(): Promise<string> {
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: GMAIL_CONFIG.clientId,
      client_secret: GMAIL_CONFIG.clientSecret,
      refresh_token: GMAIL_CONFIG.refreshToken,
      grant_type: "refresh_token",
    }),
  });

  const data = await response.json();
  if (!data.access_token) {
    throw new Error(`Gmail token error: ${JSON.stringify(data)}`);
  }
  return data.access_token;
}

// --- 一次フィルタリング ---

// メルマガ・通知と判定する送信元パターン
const NOISE_SENDER_PATTERNS = [
  /noreply@/i,
  /no-reply@/i,
  /do-not-reply@/i,
  /donotreply@/i,
  /notifications?@/i,
  /notify@/i,
  /alert@/i,
  /mailer-daemon@/i,
  /postmaster@/i,
  /news(letter)?@/i,
  /info@.*\.co\.jp/i, // info@ は大半がメルマガ
  /support@.*\.(com|io|dev)/i, // SaaS系サポート通知
  /updates?@/i,
  /digest@/i,
  /billing@/i,
  /receipt@/i,
];

// メルマガ・自動通知と判定するヘッダー
function isAutoGenerated(
  headers: Array<{ name: string; value: string }>,
): boolean {
  const hasListUnsubscribe = headers.some(
    (h) => h.name.toLowerCase() === "list-unsubscribe",
  );
  const precedence = headers
    .find((h) => h.name.toLowerCase() === "precedence")
    ?.value?.toLowerCase();
  const autoSubmitted = headers
    .find((h) => h.name.toLowerCase() === "auto-submitted")
    ?.value?.toLowerCase();
  const listId = headers.some((h) => h.name.toLowerCase() === "list-id");

  return (
    hasListUnsubscribe ||
    listId ||
    precedence === "bulk" ||
    precedence === "list" ||
    (autoSubmitted !== undefined && autoSubmitted !== "no")
  );
}

function isNoiseSender(from: string): boolean {
  return NOISE_SENDER_PATTERNS.some((pattern) => pattern.test(from));
}

export interface FilteredResult {
  actionable: GmailEmail[];
  filtered: Array<{ subject: string; from: string; reason: string }>;
}

// --- Helpers ---

export interface GmailEmail {
  id: string;
  threadId: string;
  from: string;
  to: string;
  subject: string;
  date: string;
  body: string;
}

function decodeBase64Url(str: string): string {
  const base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  return Buffer.from(base64, "base64").toString("utf-8");
}

function extractHeader(
  headers: Array<{ name: string; value: string }>,
  name: string,
): string {
  return (
    headers.find((h) => h.name.toLowerCase() === name.toLowerCase())?.value ||
    ""
  );
}

function extractBody(payload: Record<string, unknown>): string {
  const mimeType = payload.mimeType as string | undefined;
  const body = payload.body as { data?: string } | undefined;
  const parts = payload.parts as Record<string, unknown>[] | undefined;

  if (mimeType === "text/plain" && body?.data) {
    return decodeBase64Url(body.data);
  }

  if (parts) {
    for (const part of parts) {
      const partBody = part.body as { data?: string } | undefined;
      if (part.mimeType === "text/plain" && partBody?.data) {
        return decodeBase64Url(partBody.data);
      }
    }
    for (const part of parts) {
      const partBody = part.body as { data?: string } | undefined;
      if (part.mimeType === "text/html" && partBody?.data) {
        const html = decodeBase64Url(partBody.data);
        return html
          .replace(/<[^>]*>/g, " ")
          .replace(/&nbsp;/g, " ")
          .replace(/\s+/g, " ")
          .trim();
      }
    }
    for (const part of parts) {
      if (part.parts) {
        const nested = extractBody(part);
        if (nested) return nested;
      }
    }
  }

  return "";
}

// RFC 2822 メール構築ヘルパー
function buildRawEmail(
  to: string,
  subject: string,
  body: string,
  inReplyTo?: string,
  references?: string,
): string {
  const lines = [
    `To: ${to}`,
    `Subject: ${subject}`,
    ...(inReplyTo ? [`In-Reply-To: ${inReplyTo}`, `References: ${references || inReplyTo}`] : []),
    `Content-Type: text/plain; charset=UTF-8`,
    "",
    body,
  ];
  return lines.join("\r\n");
}

function encodeRawEmail(raw: string): string {
  return Buffer.from(raw)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

// --- メッセージ取得（共通） ---

async function fetchMessages(
  accessToken: string,
  query: string,
  maxResults: number,
): Promise<{ emails: GmailEmail[]; filtered: FilteredResult["filtered"] }> {
  const listUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(query)}&maxResults=${maxResults}`;

  const listRes = await fetch(listUrl, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  const listData = (await listRes.json()) as {
    messages?: Array<{ id: string }>;
  };

  if (!listData.messages || listData.messages.length === 0) {
    return { emails: [], filtered: [] };
  }

  const emails: GmailEmail[] = [];
  const filtered: FilteredResult["filtered"] = [];

  for (const msg of listData.messages) {
    const msgUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=full`;
    const msgRes = await fetch(msgUrl, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    const msgData = (await msgRes.json()) as {
      id: string;
      threadId: string;
      snippet?: string;
      payload?: Record<string, unknown>;
    };

    const headers =
      (msgData.payload?.headers as Array<{ name: string; value: string }>) ||
      [];
    const from = extractHeader(headers, "From");
    const subject = extractHeader(headers, "Subject");

    // 一次フィルタリング: メルマガ・通知を除外
    if (isAutoGenerated(headers)) {
      filtered.push({ subject, from, reason: "自動通知/メルマガ（ヘッダー判定）" });
      continue;
    }
    if (isNoiseSender(from)) {
      filtered.push({ subject, from, reason: "通知系送信元" });
      continue;
    }

    const body = msgData.payload ? extractBody(msgData.payload) : "";

    emails.push({
      id: msgData.id,
      threadId: msgData.threadId,
      from,
      to: extractHeader(headers, "To"),
      subject,
      date: extractHeader(headers, "Date"),
      body: body.slice(0, 1500),
    });
  }

  return { emails, filtered };
}

// --- 公開API ---

/**
 * 未読メールを取得し、一次フィルタ後のメールをClaudeに分析させるための文字列を返す
 */
export async function getUnreadEmails(
  maxResults: number = 20,
): Promise<string> {
  if (!GMAIL_CONFIG.refreshToken) {
    return "Gmail APIが未設定です。GMAIL_REFRESH_TOKEN を .env に追加してください。";
  }

  const accessToken = await getAccessToken();
  const { emails, filtered } = await fetchMessages(
    accessToken,
    "is:unread in:inbox newer_than:2d",
    maxResults,
  );

  if (emails.length === 0 && filtered.length === 0) {
    return "直近2日間の未読メールはありません。";
  }

  const lines: string[] = [];

  // フィルタ済みサマリー
  if (filtered.length > 0) {
    lines.push(
      `【自動除外】${filtered.length}件のメルマガ/通知を除外しました：`,
    );
    for (const f of filtered) {
      lines.push(`  • ${f.subject}（${f.reason}）`);
    }
    lines.push("");
  }

  if (emails.length === 0) {
    lines.push("返信候補のメールはありません。除外されたメールはすべてメルマガ/通知でした。");
    return lines.join("\n");
  }

  // 要対応メール
  lines.push(`【要確認メール】${emails.length}件\n`);

  emails.forEach((email, i) => {
    lines.push(
      `--- メール${i + 1} (ID: ${email.id}) ---`,
      `差出人: ${email.from}`,
      `件名: ${email.subject}`,
      `日時: ${email.date}`,
      `本文:\n${email.body}`,
      "",
    );
  });

  lines.push(
    "\n以上のメールを分析し、以下のフォーマットで回答してください：",
    "",
    "【返信が必要なメール】",
    "各メールについて：",
    "• メールID: （IDをそのまま記載）",
    "• 優先度（🔴高 / 🟡中 / 🟢低）",
    "• 理由（なぜ返信が必要か）",
    "• 返信案（そのまま使える丁寧な日本語の返信文）",
    "",
    "【返信不要のメール】",
    "• メール件名 — 不要な理由（社内メンバー→Slack連絡 / 自動通知 等）",
    "",
    "※ 判断はシステムプロンプトのビジネスコンテキスト（組織情報・連絡手段・判断基準）に従うこと。",
    "※ ユーザーが「送って」「返信して」と言ったら send_gmail_reply ツールを使ってそのまま送信できます。",
  );

  return lines.join("\n");
}

/**
 * 指定メールへの返信下書きをGmailに作成する
 */
export async function createGmailDraft(
  messageId: string,
  replyBody: string,
): Promise<string> {
  if (!GMAIL_CONFIG.refreshToken) {
    return "Gmail APIが未設定です。GMAIL_REFRESH_TOKEN を .env に追加してください。";
  }

  const accessToken = await getAccessToken();

  const msgUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${messageId}?format=full`;
  const msgRes = await fetch(msgUrl, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  const msgData = (await msgRes.json()) as {
    threadId: string;
    payload?: { headers?: Array<{ name: string; value: string }> };
  };

  const headers = msgData.payload?.headers || [];
  const from = extractHeader(headers, "From");
  const subject = extractHeader(headers, "Subject");
  const messageIdHeader = extractHeader(headers, "Message-ID");
  const threadId = msgData.threadId;

  const replySubject = subject.startsWith("Re:") ? subject : `Re: ${subject}`;
  const rawEmail = buildRawEmail(from, replySubject, replyBody, messageIdHeader);
  const encodedMessage = encodeRawEmail(rawEmail);

  const draftUrl = "https://gmail.googleapis.com/gmail/v1/users/me/drafts";
  const draftRes = await fetch(draftUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      message: { raw: encodedMessage, threadId },
    }),
  });

  const draftData = (await draftRes.json()) as {
    id?: string;
    error?: unknown;
  };

  if (draftData.error) {
    throw new Error(`Draft creation error: ${JSON.stringify(draftData.error)}`);
  }

  return [
    "✅ Gmailに返信の下書きを作成しました。",
    `宛先: ${from}`,
    `件名: ${replySubject}`,
    `Draft ID: ${draftData.id}`,
    "",
    "Gmailの下書きフォルダから確認・送信してください。",
  ].join("\n");
}

/**
 * 指定メールへの返信を直接送信する
 */
export async function sendGmailReply(
  messageId: string,
  replyBody: string,
): Promise<string> {
  if (!GMAIL_CONFIG.refreshToken) {
    return "Gmail APIが未設定です。GMAIL_REFRESH_TOKEN を .env に追加してください。";
  }

  const accessToken = await getAccessToken();

  // 元メール情報を取得
  const msgUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${messageId}?format=full`;
  const msgRes = await fetch(msgUrl, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  const msgData = (await msgRes.json()) as {
    threadId: string;
    payload?: { headers?: Array<{ name: string; value: string }> };
  };

  const headers = msgData.payload?.headers || [];
  const from = extractHeader(headers, "From");
  const subject = extractHeader(headers, "Subject");
  const messageIdHeader = extractHeader(headers, "Message-ID");
  const threadId = msgData.threadId;

  const replySubject = subject.startsWith("Re:") ? subject : `Re: ${subject}`;
  const rawEmail = buildRawEmail(from, replySubject, replyBody, messageIdHeader);
  const encodedMessage = encodeRawEmail(rawEmail);

  // 直接送信
  const sendUrl = "https://gmail.googleapis.com/gmail/v1/users/me/messages/send";
  const sendRes = await fetch(sendUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      raw: encodedMessage,
      threadId,
    }),
  });

  const sendData = (await sendRes.json()) as {
    id?: string;
    error?: unknown;
  };

  if (sendData.error) {
    throw new Error(`Send error: ${JSON.stringify(sendData.error)}`);
  }

  return [
    "✅ 返信を送信しました。",
    `宛先: ${from}`,
    `件名: ${replySubject}`,
    `Message ID: ${sendData.id}`,
  ].join("\n");
}

// --- ミラーサイト通知メールの送信失敗監視 ---

export interface MirrorBounce {
  id: string;
  date: string;
  subject: string;
  snippet: string;
}

/**
 * ミラーサイト通知メールの送信失敗を検知する。
 *
 * TC事業者ミラーの自動返信・事業者通知は takahashi@ の「Send mail as」エイリアス
 * (toiretsumari.center@gmail.com) 経由で送られる。そのアプリパスワードが失効すると、
 * GmailApp.sendEmail は実行時例外を出さないまま配信段階で 535 BadCredentials により
 * 全ミラーの送信がサイレントにバウンスする。mailer-daemon からの該当バウンスを抽出する。
 *
 * 背景: 2026-06-13、アプリPW失効で全ミラー通知が約21時間サイレント停止した事故の再発防止。
 */
export async function findMirrorBounces(
  windowHours: number = 2,
): Promise<MirrorBounce[]> {
  if (!GMAIL_CONFIG.refreshToken) {
    console.warn("[MirrorBounce] GMAIL_REFRESH_TOKEN 未設定のため監視をスキップ。");
    return [];
  }

  const accessToken = await getAccessToken();
  const query = `from:mailer-daemon newer_than:${windowHours}h`;
  const listUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(query)}&maxResults=20`;

  const listRes = await fetch(listUrl, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  const listData = (await listRes.json()) as {
    messages?: Array<{ id: string }>;
  };
  if (!listData.messages || listData.messages.length === 0) return [];

  // エイリアスのアプリPW失効を示すバウンスのマーカー
  const FAILURE_MARKERS =
    /BadCredentials|Username and Password not accepted|5\.7\.8/i;

  const bounces: MirrorBounce[] = [];
  for (const msg of listData.messages) {
    const msgUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=full`;
    const msgRes = await fetch(msgUrl, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    const msgData = (await msgRes.json()) as {
      id: string;
      threadId: string;
      snippet?: string;
      payload?: Record<string, unknown>;
    };

    const headers =
      (msgData.payload?.headers as Array<{ name: string; value: string }>) ||
      [];
    const subject = extractHeader(headers, "Subject");
    const body = msgData.payload ? extractBody(msgData.payload) : "";
    const haystack = `${subject}\n${msgData.snippet || ""}\n${body}`;

    if (!FAILURE_MARKERS.test(haystack)) continue;

    bounces.push({
      id: msgData.id,
      date: extractHeader(headers, "Date"),
      subject,
      snippet: (msgData.snippet || body).slice(0, 200),
    });
  }

  return bounces;
}
